#ifndef SERVO_H_
#define SERVO_H_

#define PMWL0		IOPORT_CREATE_PIN(PIOA, 19)
#define PMWL0_PERIPHERAL	PIO_TYPE_PIO_PERIPH_B
#define PWML0_CHANNEL		PWM_CHANNEL_0

#define PMWL1		IOPORT_CREATE_PIN(PIOA, 20)
#define PMWL1_PERIPHERAL	PIO_TYPE_PIO_PERIPH_B
#define PWML1_CHANNEL		PWM_CHANNEL_1

#define PWM_CLOCKSOURCE_FREQ 1000000
#define PWM_FREQ 50
#define PWM_PERIOD_TICKS PWM_CLOCKSOURCE_FREQ/PWM_FREQ
#define PULSE_WIDTH_FULL_LEFT_TICKS 300
#define PULSE_WIDTH_CENTER_TICKS 600
#define PULSE_WIDTH_FULL_RIGHT_TICKS 1500

void servo_config();
void moveservo(unsigned short chan, int duty);

#endif